apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-api
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: sa-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-api
    spec:
      containers:
        - image: sa/api
          imagePullPolicy: IfNotPresent
          name: sa-api
          ports:
            - containerPort: 8080
